# Generated by Django 2.1.4 on 2018-12-04 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Позиция')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='День')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Конец')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('await', 'Ожидание'), ('confirm', 'Подтвержена'), ('work', 'В работе'), ('done', 'Выполнена'), ('closed', 'Закрыта')], default='await', max_length=16, verbose_name='Статус')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Последнее обновление')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Окончание работы')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.Client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('norm_hour', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Норма-час')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.WorkType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
