# Generated by Django 2.1.4 on 2018-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Рабочий график', 'verbose_name_plural': 'Рабочие графики'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Вид работы', 'verbose_name_plural': 'Виды работ'},
        ),
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
    ]
