# Generated by Django 2.1.4 on 2019-01-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_auto_20190110_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='work',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.Car', verbose_name='Автомобиль'),
        ),
    ]
