# Generated by Django 2.1.4 on 2019-01-12 13:16

from django.db import migrations, models
import django.db.models.deletion


def fill_work_type_name(apps, schema_editor):
    WorkType = apps.get_model('autoservice', 'WorkType')
    WorkTypeName = apps.get_model('autoservice', 'WorkTypeName')
    for work in WorkType.objects.all():
        name = WorkTypeName.objects.create(
            title=work.title,
            description=work.description
        )
        work.name_id = name.id
        work.save()


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_auto_20190112_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTypeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.AddField(
            model_name='worktype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktype',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoservice.WorkTypeName', verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.RunPython(fill_work_type_name),
        migrations.RenameModel(
            old_name='Work',
            new_name='Request',
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='title',
        ),
    ]
