# Generated by Django 2.1.4 on 2019-01-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_auto_20190112_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('year_start', models.IntegerField(max_length=5, verbose_name='Год начала')),
                ('year_end', models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Год окончания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.Car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Поколение',
                'verbose_name_plural': 'Поколения',
            },
        ),
        migrations.AddField(
            model_name='worktypename',
            name='category',
            field=models.CharField(choices=[('diagnostics', 'Диагностика'), ('repair', 'Ремонт'), ('carcase', 'Кузовной')], default='diagnostics', max_length=16, verbose_name='Категория'),
        ),
    ]
