# Generated by Django 2.1.4 on 2019-01-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0007_auto_20190113_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargeneration',
            name='year_end',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
        migrations.AlterField(
            model_name='cargeneration',
            name='year_start',
            field=models.SmallIntegerField(verbose_name='Год начала'),
        ),
    ]
