# Generated by Django 2.1.4 on 2019-01-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0009_auto_20190113_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.CarType', verbose_name='Тип автомобиля'),
        ),
    ]
